export interface CategoryData {
  id: number;
  name: string;
  slug: string;
  parent: number;
  count: number;
  description: string;
  image: string;
  icon?: string;
  badge?: string;
}

export interface DepartmentGroup {
  id: number;
  name: string;
  slug: string;
  description: string;
  image: string;
  icon: string;
  subcategories: CategoryData[];
}

export const ALL_CATEGORIES_DATA: CategoryData[] = [
  // Laptops (Parent 23)
  {
    id: 23,
    name: "Laptops",
    slug: "laptops",
    parent: 0,
    count: 0,
    description: "Shop gaming laptops, business ultrabooks, student and creator laptops with warranty and fast delivery across Pakistan.",
    image: "/images/categories/laptops.jpg",
    icon: "💻",
  },
  {
    id: 24,
    name: "New Laptops",
    slug: "new-laptops",
    parent: 23,
    count: 0,
    description: "Brand new laptops in Pakistan with full manufacturer warranty and fast nationwide delivery.",
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80",
    badge: "Brand New",
  },
  {
    id: 27,
    name: "Used Laptops",
    slug: "used-laptops",
    parent: 23,
    count: 0,
    description: "Tested used laptops in Pakistan — reliable, budget-friendly machines with warranty support.",
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
    badge: "Certified Pre-Owned",
  },
  {
    id: 25,
    name: "Gaming Laptops",
    slug: "gaming-laptops",
    parent: 23,
    count: 0,
    description: "High-performance gaming laptops in Pakistan with RTX GPUs, high refresh screens and advanced cooling.",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80",
    badge: "High FPS",
  },
  {
    id: 26,
    name: "Business Laptops / Ultrabooks",
    slug: "business-laptops-ultrabooks",
    parent: 23,
    count: 0,
    description: "Thin, light and powerful business ultrabooks in Pakistan with all-day battery life and premium build.",
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 28,
    name: "Student / Budget Laptops",
    slug: "student-budget-laptops",
    parent: 23,
    count: 0,
    description: "Student and budget laptops in Pakistan offering great value for study, browsing and everyday tasks.",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 29,
    name: "Laptop Bags",
    slug: "laptop-bags",
    parent: 23,
    count: 0,
    description: "Durable, water-resistant laptop backpacks and sleeves in Pakistan to protect your machine on the move.",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 30,
    name: "Laptop Coolers",
    slug: "laptop-coolers",
    parent: 23,
    count: 0,
    description: "Cooling pads and stands in Pakistan to keep your laptop running at peak speeds without thermal throttling.",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 31,
    name: "Laptop Chargers / Adapters",
    slug: "laptop-chargers-adapters",
    parent: 23,
    count: 0,
    description: "Original and replacement laptop chargers and USB-C GaN power adapters in Pakistan.",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
  },

  // Processors / CPU (Parent 38)
  {
    id: 38,
    name: "Processors (CPU)",
    slug: "processors-cpu",
    parent: 0,
    count: 0,
    description: "Buy CPUs in Pakistan — Intel Core, AMD Ryzen and tray processors at competitive prices with nationwide delivery.",
    image: "/images/categories/processors-cpu.jpg",
    icon: "⚡",
  },
  {
    id: 39,
    name: "Intel Processors",
    slug: "intel",
    parent: 38,
    count: 0,
    description: "Intel Core i3, i5, i7 and i9 processors in Pakistan for high clock speed gaming and productivity.",
    image: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 40,
    name: "AMD Processors",
    slug: "amd",
    parent: 38,
    count: 0,
    description: "AMD Ryzen 5, 7 and 9 processors in Pakistan with incredible multi-threading and 3D V-Cache gaming performance.",
    image: "https://images.unsplash.com/photo-1555617981-d2a98f5a6b0c?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 41,
    name: "Used / Tray CPUs",
    slug: "used-tray-cpus",
    parent: 38,
    count: 0,
    description: "Tested used and tray CPUs in Pakistan — budget-friendly processors with warranty support.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80",
    badge: "Budget Friendly",
  },

  // Graphics Cards / GPU (Parent 42)
  {
    id: 42,
    name: "Graphics Cards (GPU)",
    slug: "graphics-cards-gpu",
    parent: 0,
    count: 0,
    description: "NVIDIA GeForce RTX and AMD Radeon graphics cards in Pakistan for high FPS 1080p, 1440p and 4K gaming.",
    image: "/images/categories/graphics-cards-gpu.jpg",
    icon: "🎮",
  },
  {
    id: 43,
    name: "New Graphics Cards",
    slug: "new-graphics-cards",
    parent: 42,
    count: 0,
    description: "Brand new graphics cards in Pakistan with full manufacturer warranty and fast nationwide delivery.",
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80",
    badge: "Brand New",
  },
  {
    id: 44,
    name: "Used Graphics Cards",
    slug: "used-graphics-cards",
    parent: 42,
    count: 0,
    description: "Tested used graphics cards in Pakistan — reliable performance at a lower price point.",
    image: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80",
    badge: "Tested & Verified",
  },
  {
    id: 45,
    name: "Open Box / Refurb Graphics Cards",
    slug: "open-box-refurb-graphics-cards",
    parent: 42,
    count: 0,
    description: "Open box and refurbished graphics cards in Pakistan, inspected and ready to use at discounted prices.",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
    badge: "Save More",
  },

  // Desktop PCs (Parent 32)
  {
    id: 32,
    name: "Desktop PCs",
    slug: "desktop-pcs",
    parent: 0,
    count: 0,
    description: "Prebuilt gaming PCs, custom builds, mini PCs and workstations in Pakistan with premium components and cable management.",
    image: "/images/categories/desktop-pcs.jpg",
    icon: "🖥️",
  },
  {
    id: 33,
    name: "Prebuilt Gaming Desktops",
    slug: "prebuilt-gaming-desktops",
    parent: 32,
    count: 0,
    description: "Ready-to-play prebuilt gaming desktops in Pakistan, built for high FPS gaming with fast nationwide shipping.",
    image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800&auto=format&fit=crop&q=80",
    badge: "Plug & Play",
  },
  {
    id: 34,
    name: "Custom PC Build",
    slug: "custom-pc-build",
    parent: 32,
    count: 0,
    description: "Build your dream PC in Pakistan — pick your parts, and our expert technicians assemble, stress test and deliver.",
    image: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 35,
    name: "Mini PCs",
    slug: "mini-pcs",
    parent: 32,
    count: 0,
    description: "Compact mini PCs in Pakistan for home theatre, office work, digital signage and light gaming.",
    image: "https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 36,
    name: "All-in-One PCs",
    slug: "all-in-one-pcs",
    parent: 32,
    count: 0,
    description: "Space-saving All-in-One desktop computers in Pakistan with vibrant screens and built-in speakers.",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 37,
    name: "Workstations",
    slug: "workstations",
    parent: 32,
    count: 0,
    description: "Professional workstation PCs in Pakistan for CAD, 3D rendering, video editing and heavy multitasking workloads.",
    image: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&auto=format&fit=crop&q=80",
  },

  // Memory / RAM (Parent 49)
  {
    id: 49,
    name: "Memory (RAM)",
    slug: "memory-ram",
    parent: 0,
    count: 0,
    description: "Desktop DDR4, DDR5 and laptop SODIMM RAM in Pakistan from Corsair, Kingston, G.Skill, XPG and Crucial.",
    image: "/images/categories/memory-ram.jpg",
    icon: "🧠",
  },
  {
    id: 50,
    name: "Desktop DDR4",
    slug: "desktop-ddr4",
    parent: 49,
    count: 0,
    description: "Desktop DDR4 RAM kits in Pakistan (3200MHz, 3600MHz) for gaming and work rigs.",
    image: "https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 51,
    name: "Desktop DDR5",
    slug: "desktop-ddr5",
    parent: 49,
    count: 0,
    description: "Next-gen Desktop DDR5 RAM in Pakistan (5600MHz, 6000MHz, 6400MHz) with RGB and heat spreaders.",
    image: "https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&auto=format&fit=crop&q=80",
    badge: "Next Gen",
  },
  {
    id: 52,
    name: "Laptop SODIMM DDR4",
    slug: "laptop-sodimm-ddr4",
    parent: 49,
    count: 0,
    description: "Laptop DDR4 RAM sticks in Pakistan for upgrading your notebook's multitasking and speed.",
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 53,
    name: "Laptop SODIMM DDR5",
    slug: "laptop-sodimm-ddr5",
    parent: 49,
    count: 0,
    description: "Laptop DDR5 RAM in Pakistan for newest generation gaming and creator laptops.",
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80",
  },

  // Storage (Parent 54)
  {
    id: 54,
    name: "Storage",
    slug: "storage",
    parent: 0,
    count: 0,
    description: "NVMe SSDs, SATA SSDs, HDDs, and portable external storage in Pakistan from Samsung, Kingston, WD, and Seagate.",
    image: "/images/categories/storage.jpg",
    icon: "💽",
  },
  {
    id: 55,
    name: "NVMe SSD",
    slug: "nvme-ssd",
    parent: 54,
    count: 0,
    description: "High-speed PCIe Gen4 and Gen5 NVMe SSDs in Pakistan for lightning-fast boot and load times.",
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80",
    badge: "Ultra Fast",
  },
  {
    id: 56,
    name: "SATA SSD",
    slug: "sata-ssd",
    parent: 54,
    count: 0,
    description: "SATA 2.5 inch SSDs in Pakistan — an affordable upgrade from traditional hard drives for any PC or laptop.",
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 57,
    name: "External SSD",
    slug: "external-ssd",
    parent: 54,
    count: 0,
    description: "Portable USB-C External SSDs in Pakistan for creators, backups and on-the-go storage.",
    image: "https://images.unsplash.com/photo-1628155930542-40a0291f00f4?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 59,
    name: "Internal HDD",
    slug: "internal-hdd",
    parent: 54,
    count: 0,
    description: "Internal 3.5 inch hard drives in Pakistan (2TB to 18TB) for mass file and game storage.",
    image: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 58,
    name: "External HDD",
    slug: "external-hdd",
    parent: 54,
    count: 0,
    description: "Portable 2.5 inch external hard drives in Pakistan for easy plug-and-play file backups.",
    image: "https://images.unsplash.com/photo-1628155930542-40a0291f00f4?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 60,
    name: "NAS Drives",
    slug: "nas-drives",
    parent: 54,
    count: 0,
    description: "24/7 heavy duty NAS hard drives (WD Red, Seagate IronWolf) in Pakistan for network servers.",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80",
  },

  // Motherboards (Parent 46)
  {
    id: 46,
    name: "Motherboards",
    slug: "motherboards",
    parent: 0,
    count: 0,
    description: "Intel and AMD motherboards in Pakistan (ASUS, MSI, Gigabyte, ASRock) in ATX, Micro-ATX and Mini-ITX formats.",
    image: "/images/categories/motherboards.jpg",
    icon: "🔌",
  },
  {
    id: 47,
    name: "Intel Chipset Motherboards",
    slug: "intel-chipset",
    parent: 46,
    count: 0,
    description: "LGA1700 and LGA1851 Intel motherboards (Z790, B760, H610) in Pakistan.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 48,
    name: "AMD Chipset Motherboards",
    slug: "amd-chipset",
    parent: 46,
    count: 0,
    description: "AM4 and AM5 AMD motherboards (X670, B650, A620, B550) in Pakistan with PCIe 5.0 support.",
    image: "https://images.unsplash.com/photo-1555617981-d2a98f5a6b0c?w=800&auto=format&fit=crop&q=80",
  },

  // Cooling Solutions (Parent 63)
  {
    id: 63,
    name: "Cooling Solutions",
    slug: "cooling-solutions",
    parent: 0,
    count: 0,
    description: "AIO liquid coolers, tower air coolers, ARGB case fans and thermal paste in Pakistan.",
    image: "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&auto=format&fit=crop&q=80",
    icon: "🧊",
  },
  {
    id: 65,
    name: "Liquid Coolers (AIO)",
    slug: "liquid-coolers-aio",
    parent: 63,
    count: 0,
    description: "240mm, 360mm and 420mm All-in-One liquid CPU coolers in Pakistan with LCD displays and RGB lighting.",
    image: "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&auto=format&fit=crop&q=80",
    badge: "Low Temps",
  },
  {
    id: 64,
    name: "Air Coolers",
    slug: "air-coolers",
    parent: 63,
    count: 0,
    description: "High-efficiency single and dual-tower CPU air coolers in Pakistan.",
    image: "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 66,
    name: "Case Fans",
    slug: "case-fans",
    parent: 63,
    count: 0,
    description: "120mm and 140mm PWM ARGB case fans in Pakistan for maximum airflow and aesthetics.",
    image: "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 67,
    name: "Thermal Paste / Pads",
    slug: "thermal-paste-pads",
    parent: 63,
    count: 0,
    description: "High-conductivity thermal compounds (Arctic MX-4/6, Noctua, Thermal Grizzly) in Pakistan.",
    image: "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&auto=format&fit=crop&q=80",
  },

  // Casing / Chassis (Parent 62)
  {
    id: 62,
    name: "Casing / Chassis",
    slug: "casing-chassis",
    parent: 0,
    count: 0,
    description: "Tempered glass gaming PC cases, mesh airflow cases and panoramic dual-chamber cases in Pakistan.",
    image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800&auto=format&fit=crop&q=80",
    icon: "🏢",
  },

  // Power Supplies (Parent 61)
  {
    id: 61,
    name: "Power Supplies (PSU)",
    slug: "power-supplies-psu",
    parent: 0,
    count: 0,
    description: "80 Plus Bronze, Gold, Platinum certified ATX 3.0 power supplies in Pakistan (550W to 1300W).",
    image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800&auto=format&fit=crop&q=80",
    icon: "🔋",
  },

  // Monitors (Parent 68)
  {
    id: 68,
    name: "Monitors",
    slug: "monitors",
    parent: 0,
    count: 0,
    description: "Gaming, office and creator monitors in Pakistan (144Hz, 165Hz, 240Hz, 360Hz, 4K, Curved and OLED).",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
    icon: "📺",
  },
  {
    id: 69,
    name: "Gaming Monitors",
    slug: "gaming-monitors",
    parent: 68,
    count: 0,
    description: "High refresh rate, 1ms fast IPS and OLED gaming monitors in Pakistan with G-Sync and FreeSync.",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
    badge: "165Hz+ Fast IPS",
  },
  {
    id: 70,
    name: "Office/Business Monitors",
    slug: "office-business-monitors",
    parent: 68,
    count: 0,
    description: "Crisp Full HD and 2K monitors in Pakistan for productivity, spreadsheets and everyday work.",
    image: "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 71,
    name: "Professional (Color-Accurate) Monitors",
    slug: "professional-color-accurate-monitors",
    parent: 68,
    count: 0,
    description: "Color-accurate 4K professional monitors in Pakistan with 100% sRGB / DCI-P3 for photo and video editing.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 72,
    name: "Monitor Arms / Stands",
    slug: "monitor-arms-stands",
    parent: 68,
    count: 0,
    description: "Gas spring single and dual monitor arms in Pakistan for ergonomic and clean desk setups.",
    image: "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=800&auto=format&fit=crop&q=80",
  },

  // Keyboards (Parent 73)
  {
    id: 73,
    name: "Keyboards",
    slug: "keyboards",
    parent: 0,
    count: 0,
    description: "Mechanical keyboards, wireless keyboards, hot-swappable keyboards and custom switches in Pakistan.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
    icon: "⌨️",
  },
  {
    id: 74,
    name: "Mechanical Keyboards",
    slug: "mechanical",
    parent: 73,
    count: 0,
    description: "Hot-swappable RGB mechanical keyboards (Red, Blue, Brown switches) in Pakistan.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
    badge: "Hot-Swap",
  },
  {
    id: 75,
    name: "Membrane / Wireless",
    slug: "membrane-wireless",
    parent: 73,
    count: 0,
    description: "Quiet membrane and Bluetooth multi-device wireless keyboards in Pakistan for office and home.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
  },

  // Mouse & Mousepads (Parent 76)
  {
    id: 76,
    name: "Mouse & Mousepads",
    slug: "mouse-mousepads",
    parent: 0,
    count: 0,
    description: "Ultralight gaming mice, wireless ergonomic mice and speed/control desk mousepads in Pakistan.",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
    icon: "🖱️",
  },
  {
    id: 77,
    name: "Mouse",
    slug: "mouse",
    parent: 76,
    count: 0,
    description: "High-DPI optical gaming mice and silent office mice in Pakistan.",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 78,
    name: "Gaming Mousepads",
    slug: "gaming-mousepads",
    parent: 76,
    count: 0,
    description: "Extended XXL cloth desk mats and RGB gaming mousepads in Pakistan.",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
  },

  // Audio (Parent 79)
  {
    id: 79,
    name: "Audio",
    slug: "audio",
    parent: 0,
    count: 0,
    description: "Gaming headsets, wireless earbuds, studio microphones and desktop speakers in Pakistan.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    icon: "🎧",
  },
  {
    id: 80,
    name: "Headphones / Headsets",
    slug: "headphones-headsets",
    parent: 79,
    count: 0,
    description: "7.1 surround sound gaming headsets and noise-cancelling headphones in Pakistan.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 81,
    name: "Earbuds",
    slug: "earbuds",
    parent: 79,
    count: 0,
    description: "True Wireless Stereo (TWS) low-latency earbuds in Pakistan with ANC.",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 82,
    name: "Microphones",
    slug: "microphones",
    parent: 79,
    count: 0,
    description: "USB condenser microphones for streaming, podcasting and Discord gaming in Pakistan.",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
    badge: "Studio Quality",
  },
  {
    id: 83,
    name: "Speakers",
    slug: "speakers",
    parent: 79,
    count: 0,
    description: "2.0 and 2.1 RGB desktop PC speakers and portable Bluetooth speakers in Pakistan.",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
  },

  // Apple Products (Parent 91)
  {
    id: 91,
    name: "Apple Products",
    slug: "apple-products",
    parent: 0,
    count: 0,
    description: "Original Apple MacBooks, iPads, iMacs, Mac Minis, Apple Watches and AirPods with warranty in Pakistan.",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
    icon: "🍏",
    badge: "Original Apple",
  },
  {
    id: 92,
    name: "MacBook",
    slug: "macbook",
    parent: 91,
    count: 0,
    description: "Apple MacBook Air and MacBook Pro with M2, M3 and M4 chips in Pakistan.",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
    badge: "M-Series",
  },
  {
    id: 93,
    name: "iMac",
    slug: "imac",
    parent: 91,
    count: 0,
    description: "Apple 24-inch 4.5K Retina iMac all-in-one desktop in Pakistan.",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 94,
    name: "Mac Mini",
    slug: "mac-mini",
    parent: 91,
    count: 0,
    description: "Apple Mac Mini with M-series silicon in Pakistan — tiny size, gigantic power.",
    image: "https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 95,
    name: "Mac Studio",
    slug: "mac-studio",
    parent: 91,
    count: 0,
    description: "Apple Mac Studio with M-Max and M-Ultra chips in Pakistan for professional studio work.",
    image: "https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=800&auto=format&fit=crop&q=80",
    badge: "Pro Studio",
  },
  {
    id: 96,
    name: "iPad",
    slug: "ipad",
    parent: 91,
    count: 0,
    description: "Apple iPad, iPad Air, iPad Mini and iPad Pro with Apple Pencil support in Pakistan.",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 97,
    name: "Apple Watch",
    slug: "apple-watch",
    parent: 91,
    count: 0,
    description: "Apple Watch Series and Apple Watch Ultra in Pakistan.",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 98,
    name: "AirPods",
    slug: "airpods",
    parent: 91,
    count: 0,
    description: "Apple AirPods, AirPods Pro and AirPods Max in Pakistan.",
    image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 99,
    name: "Apple Accessories",
    slug: "apple-accessories",
    parent: 91,
    count: 0,
    description: "Original MagSafe chargers, Magic Keyboard, Magic Mouse and adapters in Pakistan.",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
  },

  // Gaming (Parent 100)
  {
    id: 100,
    name: "Gaming",
    slug: "gaming",
    parent: 0,
    count: 0,
    description: "PlayStation 5, Xbox Series X/S, VR Headsets and wireless game controllers in Pakistan.",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80",
    icon: "🕹️",
  },
  {
    id: 101,
    name: "Gaming Consoles",
    slug: "gaming-consoles",
    parent: 100,
    count: 0,
    description: "PlayStation 5, Xbox Series X, Series S and Nintendo Switch in Pakistan with warranty.",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80",
    badge: "Next Gen",
  },
  {
    id: 102,
    name: "VR Headsets",
    slug: "vr-headsets",
    parent: 100,
    count: 0,
    description: "Meta Quest 3, PlayStation VR2 and PC VR headsets in Pakistan.",
    image: "https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=800&auto=format&fit=crop&q=80",
    badge: "Virtual Reality",
  },
  {
    id: 103,
    name: "Controllers / Racing Wheels",
    slug: "controllers-racing-wheels",
    parent: 100,
    count: 0,
    description: "PS5 DualSense, Xbox Wireless Controllers and Logitech G29/G923 Racing Wheels in Pakistan.",
    image: "https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&auto=format&fit=crop&q=80",
  },

  // Gaming Furniture (Parent 104)
  {
    id: 104,
    name: "Gaming Furniture",
    slug: "gaming-furniture",
    parent: 0,
    count: 0,
    description: "Ergonomic gaming chairs and motorized standing gaming desks in Pakistan.",
    image: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&auto=format&fit=crop&q=80",
    icon: "🪑",
  },
  {
    id: 105,
    name: "Gaming Chairs",
    slug: "gaming-chairs",
    parent: 104,
    count: 0,
    description: "High-back ergonomic lumbar support gaming chairs in Pakistan.",
    image: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 106,
    name: "Gaming Desks",
    slug: "gaming-desks",
    parent: 104,
    count: 0,
    description: "Carbon fiber texture RGB gaming desks and motorized sit-stand desks in Pakistan.",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80",
  },

  // Networking (Parent 85)
  {
    id: 85,
    name: "Networking",
    slug: "networking",
    parent: 0,
    count: 0,
    description: "Wi-Fi 6 Routers, Mesh systems, Gigabit switches and access points in Pakistan (TP-Link, Tenda, Asus).",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80",
    icon: "🌐",
  },
  {
    id: 86,
    name: "Routers",
    slug: "routers",
    parent: 85,
    count: 0,
    description: "Dual-band and Tri-band Gigabit Wi-Fi 6 routers in Pakistan.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 87,
    name: "Mesh WiFi Systems",
    slug: "mesh-wifi-systems",
    parent: 85,
    count: 0,
    description: "Whole home seamless Mesh Wi-Fi systems in Pakistan for zero dead zones.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 88,
    name: "Range Extenders",
    slug: "range-extenders",
    parent: 85,
    count: 0,
    description: "Plug-and-play Wi-Fi range extenders and signal boosters in Pakistan.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 89,
    name: "Switches",
    slug: "switches",
    parent: 85,
    count: 0,
    description: "5-port to 24-port Gigabit Ethernet network switches in Pakistan.",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 90,
    name: "Access Points",
    slug: "access-points",
    parent: 85,
    count: 0,
    description: "Ceiling and wall mount enterprise Wi-Fi Access Points in Pakistan.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80",
  },

  // Tablets (Parent 107)
  {
    id: 107,
    name: "Tablets",
    slug: "tablets",
    parent: 0,
    count: 0,
    description: "Samsung Galaxy Tabs, Android tablets and drawing tablets in Pakistan.",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80",
    icon: "📱",
  },
  {
    id: 108,
    name: "Android Tablets",
    slug: "android-tablets",
    parent: 107,
    count: 0,
    description: "Android tablets for media consumption, online classes and work in Pakistan.",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80",
  },

  // Smart Watches (Parent 109)
  {
    id: 109,
    name: "Smart Watches",
    slug: "smart-watches",
    parent: 0,
    count: 0,
    description: "Fitness smartwatches with AMOLED display, Bluetooth calling and heart rate monitoring in Pakistan.",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&auto=format&fit=crop&q=80",
    icon: "⌚",
  },

  // Webcams (Parent 84)
  {
    id: 84,
    name: "Webcams",
    slug: "webcams",
    parent: 0,
    count: 0,
    description: "1080p and 4K streaming webcams with autofocus and built-in noise cancellation mics in Pakistan.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
    icon: "📹",
  },

  // Office & Printing (Parent 110)
  {
    id: 110,
    name: "Office & Printing",
    slug: "office-printing",
    parent: 0,
    count: 0,
    description: "Printers, scanners, toners and projectors for home and business in Pakistan.",
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
    icon: "🖨️",
  },
  {
    id: 111,
    name: "Printers",
    slug: "printers",
    parent: 110,
    count: 0,
    description: "EcoTank, laser and all-in-one WiFi printers in Pakistan (HP, Canon, Epson).",
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 112,
    name: "Scanners",
    slug: "scanners",
    parent: 110,
    count: 0,
    description: "High-speed document and photo flatbed scanners in Pakistan.",
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 113,
    name: "Toners / Cartridges",
    slug: "toners-cartridges",
    parent: 110,
    count: 0,
    description: "Original laser toner cartridges and refill ink bottles in Pakistan.",
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 114,
    name: "Projectors",
    slug: "projectors",
    parent: 110,
    count: 0,
    description: "Smart home cinema and business conference 1080p / 4K projectors in Pakistan.",
    image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800&auto=format&fit=crop&q=80",
  },

  // UPS / Power Backup (Parent 115)
  {
    id: 115,
    name: "UPS / Power Backup",
    slug: "ups-power-backup",
    parent: 0,
    count: 0,
    description: "Line-interactive and Pure Sine Wave UPS in Pakistan (650VA to 3000VA) to protect electronics from load-shedding.",
    image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800&auto=format&fit=crop&q=80",
    icon: "⚡",
  },

  // Cables & Adapters (Parent 116)
  {
    id: 116,
    name: "Cables & Adapters",
    slug: "cables-adapters",
    parent: 0,
    count: 0,
    description: "HDMI 2.1, DisplayPort 1.4, USB-C 100W cables, multi-port docking stations and high-capacity power banks.",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
    icon: "🔌",
  },
  {
    id: 117,
    name: "HDMI / DisplayPort",
    slug: "hdmi-displayport",
    parent: 116,
    count: 0,
    description: "4K 120Hz and 8K braided HDMI 2.1 and DisplayPort 1.4 cables in Pakistan.",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 118,
    name: "USB-C / Docking Stations",
    slug: "usb-c-docking-stations",
    parent: 116,
    count: 0,
    description: "Thunderbolt and USB-C multiport hub docking stations in Pakistan for laptops.",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
  },
  {
    id: 119,
    name: "Power Banks",
    slug: "power-banks",
    parent: 116,
    count: 0,
    description: "20,000mAh to 30,000mAh 65W/100W PD fast charging power banks in Pakistan for phones and laptops.",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&auto=format&fit=crop&q=80",
  },

  // Used / Open Box (Parent 120)
  {
    id: 120,
    name: "Used / Open Box",
    slug: "used-open-box",
    parent: 0,
    count: 0,
    description: "Tested and certified pre-owned tech in Pakistan — laptops, GPUs, processors and accessories with warranty at big discounts.",
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
    icon: "🏷️",
    badge: "Big Discounts",
  },
];

export const DEPARTMENT_GROUPS: DepartmentGroup[] = [
  {
    id: 23,
    name: "Laptops",
    slug: "laptops",
    description: "Gaming laptops, business ultrabooks, student machines and laptop accessories.",
    image: "/images/categories/laptops.jpg",
    icon: "💻",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 23),
  },
  {
    id: 73,
    name: "Keyboards",
    slug: "keyboards",
    description: "Mechanical RGB keyboards, custom switches and wireless keyboards.",
    image: "/images/categories/keyboards.jpg",
    icon: "⌨️",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 73),
  },
  {
    id: 76,
    name: "Mouse & Mousepads",
    slug: "mouse-mousepads",
    description: "Ultralight wireless gaming mice, ergonomic office mice and desk pads.",
    image: "/images/categories/mouse-mousepads.jpg",
    icon: "🖱️",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 76),
  },
  {
    id: 68,
    name: "Monitors",
    slug: "monitors",
    description: "High refresh gaming screens, 4K productivity displays and monitor arms.",
    image: "/images/categories/monitors.jpg",
    icon: "📺",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 68),
  },
  {
    id: 42,
    name: "Graphics Cards (GPU)",
    slug: "graphics-cards-gpu",
    description: "New, used and refurbished NVIDIA RTX and AMD Radeon graphics cards.",
    image: "/images/categories/graphics-cards-gpu.jpg",
    icon: "🎮",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 42),
  },
  {
    id: 38,
    name: "Processors (CPU)",
    slug: "processors-cpu",
    description: "Intel Core, AMD Ryzen and tested tray CPUs for gaming and workstations.",
    image: "/images/categories/processors-cpu.jpg",
    icon: "⚡",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 38),
  },
  {
    id: 32,
    name: "Desktop PCs",
    slug: "desktop-pcs",
    description: "Prebuilt gaming rigs, custom PC builds, mini PCs and professional workstations.",
    image: "/images/categories/desktop-pcs.jpg",
    icon: "🖥️",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 32),
  },
  {
    id: 79,
    name: "Audio & Streaming",
    slug: "audio",
    description: "Gaming headsets, studio microphones, TWS earbuds and desktop speakers.",
    image: "/images/categories/audio.jpg",
    icon: "🎧",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 79),
  },
  {
    id: 91,
    name: "Apple Store",
    slug: "apple-products",
    description: "MacBook, iMac, Mac Mini, iPad, Apple Watch, AirPods and original accessories.",
    image: "/images/categories/apple-products.jpg",
    icon: "🍏",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 91),
  },
  {
    id: 49,
    name: "Memory (RAM)",
    slug: "memory-ram",
    description: "High speed Desktop & Laptop DDR4 and DDR5 memory modules.",
    image: "/images/categories/memory-ram.jpg",
    icon: "🧠",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 49),
  },
  {
    id: 54,
    name: "Storage Drives",
    slug: "storage",
    description: "PCIe NVMe Gen4/Gen5 SSDs, SATA SSDs, HDDs and external drives.",
    image: "/images/categories/storage.jpg",
    icon: "💽",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 54),
  },
  {
    id: 46,
    name: "Motherboards",
    slug: "motherboards",
    description: "Intel LGA1700/1851 and AMD AM4/AM5 gaming motherboards.",
    image: "/images/categories/motherboards.jpg",
    icon: "🔌",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 46),
  },
  {
    id: 63,
    name: "Cooling & Cases",
    slug: "cooling-solutions",
    description: "AIO liquid coolers, tower air coolers, case fans and PC cases.",
    image: "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&auto=format&fit=crop&q=80",
    icon: "🧊",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 63),
  },
  {
    id: 100,
    name: "Gaming & VR",
    slug: "gaming",
    description: "PlayStation, Xbox, Meta Quest VR and wireless gaming controllers.",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80",
    icon: "🕹️",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 100),
  },
  {
    id: 85,
    name: "Networking",
    slug: "networking",
    description: "Wi-Fi 6 routers, mesh systems, gigabit switches and access points.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80",
    icon: "🌐",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 85),
  },
  {
    id: 110,
    name: "Office & Printing",
    slug: "office-printing",
    description: "Inkjet and laser printers, toners, document scanners and projectors.",
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80",
    icon: "🖨️",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 110),
  },
  {
    id: 116,
    name: "Cables & Power",
    slug: "cables-adapters",
    description: "HDMI 2.1, DisplayPort, USB-C docks, power supplies, UPS backups and power banks.",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
    icon: "🔌",
    subcategories: ALL_CATEGORIES_DATA.filter((c) => c.parent === 116),
  },
  {
    id: 120,
    name: "Used & Open Box",
    slug: "used-open-box",
    description: "Certified pre-owned laptops, GPUs, processors and components at discounted prices.",
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
    icon: "🏷️",
    subcategories: [],
  },
];

export function getCategoryBySlug(slug: string): CategoryData | undefined {
  const s = slug.toLowerCase();
  return ALL_CATEGORIES_DATA.find((c) => c.slug.toLowerCase() === s);
}

export function getChildCategories(parentId: number): CategoryData[] {
  return ALL_CATEGORIES_DATA.filter((c) => c.parent === parentId);
}
